server:
  port: 8080
  ssl:
    bundle: "server"
    enabled-protocols: TLSv1.3

spring:
  ssl:
    bundle:
      jks:
        server:
          key:
            alias: "server"
          keystore:
            location: "classpath:localhost.p12"
            password: "localpassword"
            type: "PKCS12"
      pem:
        client:
          truststore:
            certificate: "classpath:localhost.crt"

application:
  name: Hello World
  version: 1.0.0

logging:
  level:
    org.zalando.logbook: TRACE
    org.apache.http: DEBUG
  file:
    name: ./logs/hello-world.log

logbook:
  format:
    style: json
  strategy: body-only-if-status-at-least
  minimum-status: 0
  exclude:
    - /actuator/health
    - /actuator/info

management:
  endpoints.web.exposure.include: info,health
  endpoint.health.show-details: always
  endpoint.health.probes.enabled: true
  dynatrace:
    metrics:
      export:
        v1:
          technology-type: